server:
  port: 9191

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ApiProductor
          uri: lb://API-Productor
          predicates:
            - Path=/Productor/**
        - id: ApiConsumidor
          uri: lb://API-Consumidor
          predicates:
            - Path=/Consumidor/**
        - id: ApiSecurity
          uri: lb://API-Security
          predicates:
            - Path=/Security/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost



